version: '3.7'

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped

  react:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /king_of_the_hill:/data/db
    restart: unless-stopped
